### ISSUE TITLE
Missing dist/index.js file

### ISSUE THREAD

**Issue by airmonitor** [go-to-k/image-scanner-with-trivy#23]
Hello Kento.

I'm wondering if you could advise where I can find the  dist/index.js that is needed for docker build command?
I was trying to build docker image but it's failing at this step:

```
------
 > [stage-0 2/4] COPY dist/index.js /var/task/index.js:
------
Dockerfile:5
--------------------
   3 |     WORKDIR /
   4 |     
   5 | >>> COPY dist/index.js /var/task/index.js
   6 |     
   7 |     COPY --from=aquasec/trivy:latest /usr/local/bin/trivy /opt
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 2f512eb0-cd8e-4fc9-ab30-f25de56bb2bc::5pru0a83adkb3wrboq1r5ol8f: "/dist/index.js": not found

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/knht8rml3wyh2wdoqo82o4eu4


```

**Comment by go-to-k** [comment]
@airmonitor 

Thanks for your reporting!

You just run `npm(yarn) install image-scanner-with-trivy` if you use this library in your CDK code.

If you customize or run (build) it locally, you can run `npx projen build` for building it, then the next command will be run:

- https://github.com/go-to-k/image-scanner-with-trivy/blob/main/.projenrc.ts#L82-L87
- https://github.com/go-to-k/image-scanner-with-trivy/blob/main/.projen/tasks.json#L86-L98

(About `yarn build`, see below:)

- https://github.com/go-to-k/image-scanner-with-trivy/blob/main/assets/lambda/package.json#L8

This library builds the code before publishing to npm in CI.

- https://github.com/go-to-k/image-scanner-with-trivy/blob/main/.github/workflows/build.yml#L29
